import {table,action} from '../product-ui.js';import {downloadBlob} from '../../services/export-service.js';
export async function mountAudit({main,model,controller}){
 const a=model?.pack.audit,metadata=await controller.mappingMetadata();
 main.innerHTML=`<div data-audit-root><section class="page-heading"><div><span class="eyebrow">Methodology</span><h1>How the calculator works</h1><p class="lead">A practical guide to interpreting water potential, participation, result status and data-quality checks.</p></div></section>
 <section class="analysis-grid"><article class="card chart-card"><span class="eyebrow">KPI 1.1.1</span><h2>Rainfall-linked water potential</h2><p>Water contribution is calculated over the applicable reporting period using the structure method and daily water balance where required.</p></article><article class="card chart-card"><span class="eyebrow">KPI 1.1.2</span><h2>Capacity-based water potential</h2><p>Water contribution is calculated from the applicable capacity or incremental-capacity method for the structure.</p></article><article class="card chart-card"><span class="eyebrow">KPI 1.2.1</span><h2>Participation in person-days</h2><p>Participation is calculated separately from water volume and is never added to cubic metres.</p></article></section>
 <section class="card"><h2>Reading result status</h2><dl class="help-terms"><dt>Accepted</dt><dd>The calculated result meets the configured evidence and review requirements.</dd><dt>Evidence pending</dt><dd>A calculated result exists, but supporting evidence is still pending.</dd><dt>Calculated with warning</dt><dd>A calculated result exists and a warning remains visible for review.</dd><dt>Not calculated / HOLD</dt><dd>No numeric result is presented for this record.</dd><dt>Excluded</dt><dd>The record is outside the applicable calculation result.</dd><dt>Missing values</dt><dd>A blank result is not zero.</dd><dt>Units</dt><dd>Changing the display unit changes presentation only; calculation precision is preserved.</dd></dl></section>
 <section class="card"><h2>Workbook help</h2><p><a href="./templates/HUF-SS-INPUT-v1.1.xlsx">Download input template</a></p><p>Enter source data in the labelled sheets. Keep a cell blank when a value is unknown and enter 0 only when the actual value is zero. Use <strong>Prepare Data</strong> to review workbook structure, field matches and data-quality issues before calculation.</p><label>Find an input field<input data-help-search placeholder="Field, sheet or requirement"></label><div data-help-fields></div></section>
 ${a?`<section class="card"><h2>Run information</h2><p>Technical audit identifiers, hashes and software version records are kept out of normal screens and reports. They remain available in the separate audit file when specialist verification is required.</p>${table([{item:'Reporting period',value:`${a.runManifest.reportingStartDate} to ${a.runManifest.reportingEndDate}`},{item:'Calendar days',value:a.runManifest.expectedCalendarDays},{item:'Ready water records',value:a.runManifest.readyWaterRecordCount},{item:'Not-ready water records',value:a.runManifest.notReadyWaterRecordCount},{item:'HOLD water records',value:a.runManifest.holdWaterRecordCount},{item:'Excluded water records',value:a.runManifest.excludedWaterRecordCount}],[{key:'item',label:'Item'},{key:'value',label:'Value'}])}<button class="button secondary" data-save-audit>Download audit file</button></section>`:''}
 </div>`;
 if(a)action(main,'[data-save-audit]',()=>downloadBlob(new Blob([JSON.stringify(a,null,2)],{type:'application/json'}),'Water_Potential_Standard_Audit.json'));
 const fields=()=>{const term=main.querySelector('[data-help-search]').value.toLowerCase();main.querySelector('[data-help-fields]').innerHTML=table(metadata.filter(m=>JSON.stringify(m).toLowerCase().includes(term)).slice(0,100),[{key:'expectedSheet',label:'Table'},{key:'controlledField',label:'Field'},{key:'dataType',label:'Type'},{key:'unitFormat',label:'Unit / format'},{key:'requirementClass',label:'Requirement'}]);};main.querySelector('[data-help-search]').oninput=fields;fields();
}
