import {esc,table,action} from '../product-ui.js';import {filtersMarkup,wireFilters} from './results.js';
import {compactRows,toCsv,xlsxBlob,exportSheets,downloadBlob,auditZip,zipWithManifest} from '../../services/export-service.js';import {reportData,makePdf} from '../../services/report-service.js';import {selectResults,bulkScopes} from '../../views/result-model.js';
export function mountReports({main,model,filter,synthetic,onChange}){
 const count=selectResults(model,filter).length;
 main.innerHTML=`<div data-reports-root><section class="page-heading"><div><span class="eyebrow">Reports</span><h1>Download decision-ready outputs</h1><p class="lead">Choose the same scope you see in Results, then download clean management or technical outputs. Normal reports use readable labels; specialist audit codes stay in the separate audit package.</p></div></section>${filtersMarkup(model,filter)}
 <section class="analysis-grid"><article class="card chart-card"><span class="eyebrow">Management</span><h2>Concise report for programme review</h2><p>Cover page, executive KPIs, geography contribution, coverage, status and concise result tables.</p><button class="button primary" data-pdf-mode="management">Download management PDF</button></article><article class="card chart-card"><span class="eyebrow">Technical / M&E</span><h2>Detailed report for practitioners</h2><p>Management summary plus structure calculation basis and daily water-balance visuals where applicable.</p><button class="button primary" data-pdf-mode="technical">Download technical PDF</button></article><article class="card chart-card"><span class="eyebrow">Workbook</span><h2>Results for further analysis</h2><p>Readable XLSX sheets for summary, geography, structures, participation and data quality.</p><div class="sample-actions"><button class="button secondary" data-export="management">Management XLSX</button><button class="button secondary" data-export="technical">Technical XLSX</button></div></article></section>
 <section class="card"><div class="chart-head"><div><span class="eyebrow">Data extracts</span><h2>Simple tabular downloads</h2></div><span class="chart-unit">${count} records</span></div><div class="sample-actions"><button class="button secondary" data-export="csv" ${count?'':'disabled'}>Results CSV</button><button class="button secondary" data-export="compact">Results XLSX</button></div></section>
 <section class="card"><span class="eyebrow">Multiple geographies</span><h2>Bulk reporting</h2><p>Generate one report per geography within the selected scope, or one combined PDF.</p><label>Report type<select data-report-mode><option value="management">Management</option><option value="technical">Technical / M&E</option></select></label><label>Geography level<select data-bulk-level><option value="district">District</option><option value="block">Block</option><option value="gram_panchayat">GP</option><option value="village">Village</option><option value="structure">Structure</option></select></label><div class="sample-actions"><button class="button secondary" data-bulk>Download report bundle ZIP</button><button class="button secondary" data-combined-pdf>Download combined PDF</button></div></section>
 <details class="card"><summary>Specialist audit downloads</summary><p>These machine-readable files retain internal run, route, formula, version and hash identifiers for audit or software review. Most field users do not need them.</p><div class="sample-actions"><button class="button secondary" data-audit-json>Standard Audit JSON</button><button class="button secondary" data-audit-zip>Audit package ZIP</button></div></details>
 <section class="card"><h2>Records included in this scope</h2>${table(compactRows(model,filter,synthetic),[{key:'recordId',label:'Record'},{key:'structureName',label:'Name'},{key:'resultFamily',label:'Result'},{key:'result',label:'Value'},{key:'unit',label:'Unit'},{key:'resultStatus',label:'Status'}])}</section><p role="status" data-report-status></p></div>`;
 wireFilters(main,filter,onChange);
 const pdf=(mode)=>{const d=reportData(model,filter,synthetic,mode);downloadBlob(makePdf(d).output('blob'),`Water_Potential_${d.metadata.scope?.label||'Selected'}_${mode==='technical'?'Technical':'Management'}_Report.pdf`);main.querySelector('[data-report-status]').textContent=`Report generated from ${d.metadata.includedResultIds.length} result records.`;};
 for(const b of main.querySelectorAll('[data-pdf-mode]'))action(main,`[data-pdf-mode="${b.dataset.pdfMode}"]`,()=>pdf(b.dataset.pdfMode));
 for(const button of main.querySelectorAll('[data-export]'))action(main,`[data-export="${button.dataset.export}"]`,async()=>{const kind=button.dataset.export;if(kind==='csv')downloadBlob(new Blob([toCsv(compactRows(model,filter,synthetic))],{type:'text/csv;charset=utf-8'}),'Water_Potential_Results.csv');else downloadBlob(await xlsxBlob(exportSheets(model,filter,synthetic,kind)),`Water_Potential_${kind==='technical'?'Technical':'Results'}_Workbook.xlsx`);});
 action(main,'[data-audit-json]',()=>downloadBlob(new Blob([JSON.stringify(model.pack.audit,null,2)],{type:'application/json'}),'Water_Potential_Standard_Audit.json'));action(main,'[data-audit-zip]',async()=>downloadBlob(await auditZip(model),'Water_Potential_Audit_Package.zip'));
 const bulkData=()=>bulkScopes(model,filter,main.querySelector('[data-bulk-level]').value).map(s=>reportData(model,s.filter,synthetic,main.querySelector('[data-report-mode]').value));
 action(main,'[data-bulk]',async()=>{const reports=bulkData();if(!reports.length)throw new Error('No matching geographies at this level.');const files={};reports.forEach((d,i)=>{files[`${String(i+1).padStart(3,'0')}_${d.metadata.scope.label.replace(/[^\p{L}\p{N}_ -]/gu,'_')}.pdf`]=makePdf(d).output('arraybuffer');});files['scope-results.csv']=toCsv(compactRows(model,filter,synthetic));files['SCOPES.json']=JSON.stringify(reports.map(d=>({scope:d.metadata.scope,reportingStartDate:d.metadata.reportingStartDate,reportingEndDate:d.metadata.reportingEndDate})),null,2);downloadBlob(await zipWithManifest(files,{scope:filter.scope||model.defaultScope,synthetic}),'Water_Potential_Report_Bundle.zip');});
 action(main,'[data-combined-pdf]',()=>{const reports=bulkData();if(!reports.length)throw new Error('No matching geographies at this level.');downloadBlob(makePdf(reports).output('blob'),'Water_Potential_Combined_Report.pdf');});
}
