import fs from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';
import {runFixture} from '../fixtures/runtime.mjs';import {xlsxBlob} from '../../services/export-service.js';
const destination=path.resolve(process.env.HUF_PERFORMANCE_DIR||'/tmp/huf-performance');await fs.mkdir(destination,{recursive:true});
for(const calendar of ['nonleap','leap']){
 const original=await runFixture(calendar+'/'+(calendar==='leap'?'GOLDEN_E2E_LEAP_FY2023-24.xlsx':'GOLDEN_E2E_NONLEAP_FY2024-25.xlsx')),detail=original.getPreparationDetail(),sheets={'00_Instructions':[{Instructions:'SYNTHETIC CAPACITY ACCEPTANCE ONLY. NOT PRODUCTION DATA.'}]};
 for(const table of detail.tables){const shared=['01_Control','06_Daily_Rainfall','07_Hydro_Params'].includes(table.expectedSheet),rows=[];for(let copy=0;copy<(shared?1:50);copy++)for(const r of table.records){const values={};for(const c of Object.values(r.cells)){let value=c.sourceValue;if(typeof value==='string'&&!shared&&/^(S-|PD-\d|P-\d|CAT-|CSL-|EVD-|SIL-|STA-)/.test(value))value+='-COPY'+copy;if(table.expectedSheet==='02_Structures'&&['STR-010','STR-011','STR-012','STR-013'].includes(c.fieldId))value+=' Capacity '+(c.fieldId==='STR-010'?copy%5:copy);values[c.sourceHeader]=value;}rows.push(values);}if(!rows.length)rows.push(Object.fromEntries(original.getMappingMetadata().filter(f=>f.expectedSheet===table.expectedSheet).map(f=>[f.controlledField,null])));sheets[table.expectedSheet]=rows;}
 sheets['99_Lookups']=[{Notice:'Controlled data fields and methods are unchanged; this is a generated synthetic acceptance input.'}];
 const structures=sheets['02_Structures'],people=sheets['10_Person_Days'];if(structures.length!==1000||people.length!==1000||new Set(structures.map(r=>r.District)).size!==5||new Set(structures.map(r=>r.Village)).size<50)throw Error('Declared workload dimensions not satisfied');
 const bytes=new Uint8Array(await(await xlsxBlob(sheets)).arrayBuffer()),name=`SYNTHETIC_CAPACITY_1000_${calendar}.xlsx`;await fs.writeFile(path.join(destination,name),bytes);await fs.writeFile(path.join(destination,name+'.json'),JSON.stringify({synthetic:true,sourceGolden:calendar,structures:1000,personDayRecords:1000,rainfallRows:sheets['06_Daily_Rainfall'].length,sha256:crypto.createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length},null,2));console.log(name,bytes.length);
}
