import { sha256Hex } from '../core/hash.js';

function deepFreeze(value){if(!value||typeof value!=='object'||ArrayBuffer.isView(value)||Object.isFrozen(value))return value;Object.freeze(value);for(const child of Object.values(value))deepFreeze(child);return value;}
function stableJson(value){if(Array.isArray(value))return `[${value.map(stableJson).join(',')}]`;if(value&&typeof value==='object')return `{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${stableJson(value[k])}`).join(',')}}`;return JSON.stringify(value);}
const text=v=>v===null||v===undefined?'':String(v).trim();
function table(snapshot,name){return snapshot.tables.find(t=>t.expectedSheet===name)||{records:[]};}
function value(record,id){return record?.values?.[id]??null;}
function isoNow(){return new Date().toISOString();}
function runId(){const id=globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(16).slice(2)}`;return `RUN-${id}`;}
function resultInventory(calculationSnapshot,assuranceSnapshot){
  const aByResult=new Map([...(assuranceSnapshot.waterAssurance||[]),...(assuranceSnapshot.personDayAssurance||[])].map(a=>[a.resultId,a]));
  const water=(calculationSnapshot.waterCalculations||[]).map(x=>({resultType:'water',resultId:x.calculationId,entityId:x.structureRecordId,routeId:x.waterRouteId,component:x.waterComponent,calculationStatus:x.calculationStatus,numericResult:x.resultM3,assuranceStatus:aByResult.get(x.calculationId)?.assuranceStatus??null}));
  const pd=(calculationSnapshot.personDayCalculations||[]).map(x=>({resultType:'person-day',resultId:x.personDayCalculationId,entityId:x.personDayRecordId,routeId:x.personDayRouteId,component:'KPI-1.2.1',calculationStatus:x.calculationStatus,numericResult:x.calculatedPersonDays,assuranceStatus:aByResult.get(x.personDayCalculationId)?.assuranceStatus??null}));
  return [...water,...pd];
}
function issueRows(validationSnapshot,calculationSnapshot,aggregationSnapshot,runIdValue,rulebookVersion){
  const rows=[];let seq=0;const push=(x)=>rows.push({validationIssueId:`ISS-E09-${String(++seq).padStart(4,'0')}`,runId:runIdValue,...x,rulebookVersion});
  for(const i of validationSnapshot.issues||[])push({ruleId:i.ruleId,severity:i.severity,scopeEffect:i.scopeEffect,entityType:i.entityType,entityId:i.entityId,sheet:i.sheet,fieldId:i.fieldId,sourceRowNumber:i.sourceRowNumber,message:i.message,observedValue:i.observedValue??null,expectedRule:i.expected??null,readinessEffect:i.readinessEffect,resolutionStatus:i.severity==='WARNING'?'accepted-warning':['ROUTE_CONTROL','QA_CONTROL'].includes(i.severity)?'accepted-warning':'open',resolutionNote:i.note??null,resolvedAt:i.severity==='WARNING'?isoNow():null});
  for(const q of calculationSnapshot.calculationQa?.ruleResults||[]){if(q.status==='FAIL')push({ruleId:q.ruleId,severity:'BLOCKING_ERROR',scopeEffect:'RECORD_BLOCK',entityType:'calculation',entityId:q.structureRecordId??null,sheet:null,fieldId:null,sourceRowNumber:null,message:q.name||'Calculation QA failure',observedValue:null,expectedRule:'Frozen Design 4 calculation QA rule must pass.',readinessEffect:'not_ready',resolutionStatus:'open',resolutionNote:(q.problems||[]).join('; '),resolvedAt:null});}
  for(const q of aggregationSnapshot.aggregationQa?.ruleResults||[]){if(q.status==='FAIL')push({ruleId:q.ruleId,severity:'BLOCKING_ERROR',scopeEffect:'AGGREGATION_BLOCK',entityType:'aggregation',entityId:'project',sheet:null,fieldId:null,sourceRowNumber:null,message:q.name||'Aggregation QA failure',observedValue:null,expectedRule:'Frozen Design 4 aggregation QA rule must pass.',readinessEffect:'aggregate_not_ready',resolutionStatus:'open',resolutionNote:(q.problems||[]).join('; '),resolvedAt:null});}
  return rows;
}
function outcomeFor(engine,{validationSnapshot,routingSnapshot,calculationSnapshot,assuranceSnapshot,aggregationSnapshot}){
  if(engine==='E04')return validationSnapshot.stats?.blockingIssueCount?'warning':validationSnapshot.stats?.warningIssueCount?'warning':'success';
  if(engine==='E05')return routingSnapshot.status==='routing_ready'?'success':'warning';
  if(engine==='E06')return calculationSnapshot.stats?.qaFailedWaterResults?'blocked':calculationSnapshot.stats?.notCalculatedWaterResults?'warning':'success';
  if(engine==='E07')return (assuranceSnapshot.statusCounts?.['calculated-warning']||0)+(assuranceSnapshot.statusCounts?.['provisional-evidence-pending']||0)+(assuranceSnapshot.statusCounts?.['not-calculated']||0)>0?'warning':'success';
  if(engine==='E08')return aggregationSnapshot.status==='aggregation_complete'?'success':'blocked';
  return 'success';
}
function auditEvents({runIdValue,runTimestamp,sourceSha,mappingSnapshot,canonicalSnapshot,validationSnapshot,routingSnapshot,calculationSnapshot,assuranceSnapshot,aggregationSnapshot,versionIds,auditPolicy,manifestContentHash}){
  const hashes={E01:sourceSha,E02:mappingSnapshot.snapshotHash,E03:canonicalSnapshot.canonicalSnapshotHash,E04:validationSnapshot.validationSnapshotHash,E05:routingSnapshot.routingSnapshotHash,E06:calculationSnapshot.calculationSnapshotHash,E07:assuranceSnapshot.assuranceSnapshotHash,E08:aggregationSnapshot.aggregationSnapshotHash,E09:manifestContentHash};
  const engines=['E01','E02','E03','E04','E05','E06','E07','E08','E09'];
  return engines.map((engine,i)=>{const spec=(auditPolicy.pipeline_events||[]).find(x=>x.engine===engine)||{};return {auditEventId:`AUD-E09-${String(i+1).padStart(3,'0')}`,runId:runIdValue,timestamp:runTimestamp,engine,eventType:spec.event_type||'pipeline',entityType:engine==='E01'?'workbook':'run',entityId:engine==='E01'?sourceSha:runIdValue,actionRuleId:spec.action||null,beforeHash:i===0?null:hashes[engines[i-1]],afterHash:hashes[engine],outcome:engine==='E09'?'success':outcomeFor(engine,{validationSnapshot,routingSnapshot,calculationSnapshot,assuranceSnapshot,aggregationSnapshot}),issueId:null,formulaIds:engine==='E06'?[...new Set((calculationSnapshot.waterCalculations||[]).flatMap(x=>x.formulaIds||[]).concat((calculationSnapshot.personDayCalculations||[]).flatMap(x=>x.formulaIds||[])))]:[],versionIds,userAction:engine==='E02'?'mapping-confirmed':null,eventNote:engine==='E09'?'Run manifest and standard audit package finalized in browser memory.':null};});
}
function safeAuditExport(snapshot){
  return {schema:'HUF-E09-STANDARD-AUDIT-EXPORT-v1.0',generatedAt:snapshot.runTimestamp,runManifest:snapshot.runManifest,validationIssues:snapshot.validationIssues.map(({observedValue,...x})=>x),auditEvents:snapshot.auditEvents,resultInventory:snapshot.resultInventory,projectSummary:snapshot.projectSummary,versionIds:snapshot.versionIds,snapshotHashes:snapshot.snapshotHashes,auditPackageContentHash:snapshot.auditPackageContentHash,notes:['Standard audit export excludes source workbook bytes, raw workbook rows, full canonical tables and raw participant names.','This export contains synthetic/project-derived metadata and result statuses only; source data remains browser-memory-only.']};
}
function publicSummary(snapshot){return {engine:'E09',engineContractVersion:'E09-v0.9.0',runId:snapshot.runId,runTimestamp:snapshot.runTimestamp,sourceSessionId:snapshot.sourceSessionId,sourceWorkbookSha256:snapshot.sourceWorkbookSha256,auditPolicyVersion:snapshot.auditPolicyVersion,runManifestContentHash:snapshot.runManifestContentHash,auditPackageContentHash:snapshot.auditPackageContentHash,auditSnapshotHash:snapshot.auditSnapshotHash,status:snapshot.status,stats:snapshot.stats,runManifest:snapshot.runManifest,versionIds:snapshot.versionIds,snapshotHashes:snapshot.snapshotHashes,projectSummary:snapshot.projectSummary,issuePreview:snapshot.validationIssues.slice(0,80).map(({observedValue,...x})=>x),auditEvents:snapshot.auditEvents,notes:['Engine 9 finalizes provenance only; it never changes E01–E08 source, mapping, canonical, validation, routing, calculation, assurance or aggregation truth.','Run manifest records source SHA-256, controlling versions and every immutable downstream snapshot hash.','Audit events are observable pipeline events and controlled actions; they do not contain hidden reasoning.','The standard audit export excludes raw workbook bytes, full canonical tables and raw participant names.','Project data is never encoded in the URL and no backend persistence is used.']};}

export async function evaluateAudit({intakeSummary,mappingSnapshot,canonicalSnapshot,validationSnapshot,routingSnapshot,calculationSnapshot,assuranceSnapshot,aggregationSnapshot,appConfig,auditPolicy}){
  if(!intakeSummary?.sourceWorkbook?.sha256)throw new Error('Engine 9 requires the finalized Engine 1 intake summary.');
  if(!mappingSnapshot?.snapshotHash||!canonicalSnapshot?.canonicalSnapshotHash||!validationSnapshot?.validationSnapshotHash||!routingSnapshot?.routingSnapshotHash||!calculationSnapshot?.calculationSnapshotHash||!assuranceSnapshot?.assuranceSnapshotHash||!aggregationSnapshot?.aggregationSnapshotHash)throw new Error('Engine 9 requires immutable snapshots from Engines 2–8.');
  if(!auditPolicy?.policy_id)throw new Error('Engine 9 audit policy is not loaded.');
  const control=table(canonicalSnapshot,'01_Control').records[0]||null,runIdValue=runId(),runTimestamp=isoNow();
  const routeStats=routingSnapshot.stats||{};
  const validationIssues=issueRows(validationSnapshot,calculationSnapshot,aggregationSnapshot,runIdValue,validationSnapshot.validationRulebookVersion);
  const blockingIssueCount=validationIssues.filter(i=>['BLOCKING_ERROR','SCOPED_ERROR'].includes(i.severity)).length;
  const warningIssueCount=validationIssues.filter(i=>i.severity==='WARNING').length;
  const versionIds={appVersion:appConfig.appVersion,routeRegistry:routingSnapshot.routeRegistryVersion,formulaCatalog:calculationSnapshot.formulaCatalogVersion,inputSchema:canonicalSnapshot.schemaVersion,canonicalizationPolicy:canonicalSnapshot.canonicalizationPolicyVersion,validationRulebook:validationSnapshot.validationRulebookVersion,routingPolicy:routingSnapshot.routingPolicyVersion,assurancePolicy:assuranceSnapshot.assurancePolicyVersion,aggregationPolicy:aggregationSnapshot.aggregationPolicyVersion,auditPolicy:auditPolicy.policy_id,resultSchema:appConfig.designVersions?.resultSchema||'HUF-D5-RESULT-AUDIT-REPORTING-v1.0',uatContract:appConfig.designVersions?.uatContract||'HUF-D6-GOLDEN-UAT-v1.0'};
  const snapshotHashes={sourceWorkbookSha256:intakeSummary.sourceWorkbook.sha256,mappingSnapshotHash:mappingSnapshot.snapshotHash,canonicalSnapshotHash:canonicalSnapshot.canonicalSnapshotHash,validationSnapshotHash:validationSnapshot.validationSnapshotHash,routingSnapshotHash:routingSnapshot.routingSnapshotHash,calculationSnapshotHash:calculationSnapshot.calculationSnapshotHash,assuranceSnapshotHash:assuranceSnapshot.assuranceSnapshotHash,aggregationSnapshotHash:aggregationSnapshot.aggregationSnapshotHash};
  const runManifest={runId:runIdValue,runTimestamp,sourceSessionId:canonicalSnapshot.sourceSessionId,sourceWorkbookName:intakeSummary.sourceWorkbook.fileName??null,sourceWorkbookSha256:intakeSummary.sourceWorkbook.sha256,sourceWorkbookSizeBytes:intakeSummary.sourceWorkbook.byteLength??null,templateVersion:value(control,'CTL-001'),projectId:value(control,'CTL-002'),projectName:value(control,'CTL-003'),piaImplementingAgency:value(control,'CTL-004'),reportingStartDate:value(control,'CTL-005'),reportingEndDate:value(control,'CTL-006'),expectedCalendarDays:validationSnapshot.calendar?.expectedDays??null,formulaCatalogVersion:calculationSnapshot.formulaCatalogVersion,capacityCatalogVersion:value(control,'CTL-011'),validationRulebookVersion:validationSnapshot.validationRulebookVersion,routeRegistryVersion:routingSnapshot.routeRegistryVersion,inputSchemaVersion:canonicalSnapshot.schemaVersion,appVersion:appConfig.appVersion,ddwRunoffMethod:value(control,'CTL-012'),ddwCalibrationId:value(control,'CTL-013'),defaultAreaMethod:value(control,'CTL-014'),mappingSnapshotHash:mappingSnapshot.snapshotHash,canonicalizationSnapshotHash:canonicalSnapshot.canonicalSnapshotHash,validationIssueCount:validationIssues.length,blockingIssueCount,warningCount:warningIssueCount,readyWaterRecordCount:(routeStats.eligibilityCounts?.eligible||0)+(routeStats.eligibilityCounts?.eligible_with_warning||0),notReadyWaterRecordCount:routeStats.eligibilityCounts?.not_ready||0,holdWaterRecordCount:routeStats.eligibilityCounts?.hold||0,excludedWaterRecordCount:routeStats.eligibilityCounts?.excluded||0,privacyMode:auditPolicy.privacy_mode_default||'standard',piiReportingPolicy:auditPolicy.pii_reporting_policy,projectDataInUrl:false,formalHufGovernanceStatus:assuranceSnapshot.externalGovernanceStatus,runNotes:value(control,'CTL-016')};
  const manifestContentHash=await sha256Hex(new TextEncoder().encode(stableJson({...runManifest,runId:undefined,runTimestamp:undefined})).buffer);
  const auditEventsList=auditEvents({runIdValue,runTimestamp,sourceSha:intakeSummary.sourceWorkbook.sha256,mappingSnapshot,canonicalSnapshot,validationSnapshot,routingSnapshot,calculationSnapshot,assuranceSnapshot,aggregationSnapshot,versionIds,auditPolicy,manifestContentHash});
  const inventory=resultInventory(calculationSnapshot,assuranceSnapshot),projectSummary=aggregationSnapshot.projectSummary;
  const standardExportCore={runManifest,validationIssues:validationIssues.map(({observedValue,...x})=>x),auditEvents:auditEventsList,resultInventory:inventory,projectSummary,versionIds,snapshotHashes};
  const auditPackageContentHash=await sha256Hex(new TextEncoder().encode(stableJson(standardExportCore)).buffer);
  const stats={validationIssues:validationIssues.length,auditEvents:auditEventsList.length,resultInventoryRecords:inventory.length,waterResults:inventory.filter(x=>x.resultType==='water').length,personDayResults:inventory.filter(x=>x.resultType==='person-day').length,projectSummaryRows:projectSummary.length,controllingVersions:Object.keys(versionIds).length,snapshotHashes:Object.keys(snapshotHashes).length};
  const status=aggregationSnapshot.status==='aggregation_complete'&&blockingIssueCount===0?'audit_complete':'audit_complete_with_upstream_not_ready';
  const core={engine:'E09',engineContractVersion:'E09-v0.9.0',runId:runIdValue,runTimestamp,sourceSessionId:canonicalSnapshot.sourceSessionId,sourceWorkbookSha256:intakeSummary.sourceWorkbook.sha256,auditPolicyVersion:auditPolicy.policy_id,runManifest,validationIssues,auditEvents:auditEventsList,resultInventory:inventory,projectSummary,versionIds,snapshotHashes,runManifestContentHash:manifestContentHash,auditPackageContentHash,stats,status};
  const auditSnapshotHash=await sha256Hex(new TextEncoder().encode(stableJson(core)).buffer);
  return deepFreeze({...core,auditSnapshotHash});
}

export async function runEngine09({config},{store,bus}){
  const state=store.getState();if(!state.intake||!state.mapping?.immutableSnapshot||!state.canonical?.immutableSnapshot||!state.validated?.immutableSnapshot||!state.routed?.immutableSnapshot||!state.calculated?.immutableSnapshot||!state.assured?.immutableSnapshot||!state.aggregated?.immutableSnapshot)throw new Error('Complete Engines 1–8 before finalizing the audit run manifest.');
  store.patchFrom('aggregation',{lifecycle:'audit_processing',audit:null,audited:null,error:null});
  try{const immutableSnapshot=await evaluateAudit({intakeSummary:state.intake,mappingSnapshot:state.mapping.immutableSnapshot,canonicalSnapshot:state.canonical.immutableSnapshot,validationSnapshot:state.validated.immutableSnapshot,routingSnapshot:state.routed.immutableSnapshot,calculationSnapshot:state.calculated.immutableSnapshot,assuranceSnapshot:state.assured.immutableSnapshot,aggregationSnapshot:state.aggregated.immutableSnapshot,appConfig:config.app,auditPolicy:config.auditPolicy});const audited=Object.freeze({immutableSnapshot,auditSnapshotHash:immutableSnapshot.auditSnapshotHash,getSnapshot:()=>immutableSnapshot,getStandardExport:()=>deepFreeze(safeAuditExport(immutableSnapshot))});const summary=publicSummary(immutableSnapshot);store.patch({lifecycle:'audit_ready',audit:summary,audited,error:null});bus?.emit('audit:completed',{runId:summary.runId,auditSnapshotHash:summary.auditSnapshotHash,status:summary.status,stats:summary.stats});return summary;}catch(error){store.patch({lifecycle:'blocked_error',error:{engine:'E09',message:error.message}});throw error;}
}

export function standardAuditExport(snapshot){return safeAuditExport(snapshot);}
