import {normalFont,boldFont} from '../vendor/fonts/dejavu-sans.js';
import {selectResults,summarizeResults,scopeMetadata} from '../views/result-model.js';

const methodName=r=>r.routeDetail?.routeName||r.routeDetail?.displayName||r.route||'Applicable calculation method';
export function reportData(model,filter,synthetic,mode='management'){
 const rows=selectResults(model,filter);return {title:'Water Potential Calculator',subtitle:'Water Potential · Participation · Reporting',mode,metadata:scopeMetadata(model,filter,synthetic),generatedAt:new Date().toISOString(),summary:summarizeResults(rows),records:rows.map(r=>({id:r.recordId,name:r.name,structureType:r.structureType,component:r.component,value:r.value,unit:r.unit,status:r.statusLabel,method:methodName(r),reason:r.assurance.statusReason,calculation:r.calculation,sourceBasis:r.sourceBasis,identity:r.identity,evidence:r.assurance.evidenceRequirements})),geography:model.scopes.filter(s=>s.parent===(filter.scope||model.defaultScope)).map(s=>({scope:s,summary:summarizeResults(rows.filter(r=>r.memberships.includes(s.key)))})).filter(s=>s.summary.length),issues:model.pack.audit.validationIssues.filter(i=>i.entityType==='workbook'||rows.some(r=>r.recordId===i.entityId||r.structureId===i.entityId)),audit:model.pack.audit};
}

export function makePdf(input){
 const reports=Array.isArray(input)?input:[input];if(!reports.length)throw new Error('No reports selected.');
 const doc=new globalThis.jspdf.jsPDF({unit:'mm',format:'a4',compress:true});doc.addFileToVFS('DejaVuSans.ttf',normalFont);doc.addFont('DejaVuSans.ttf','WPC','normal');doc.addFileToVFS('DejaVuSans-Bold.ttf',boldFont);doc.addFont('DejaVuSans-Bold.ttf','WPC','bold');
 const C={navy:[23,50,77],teal:[13,92,99],cyan:[88,170,176],gold:[215,162,54],green:[59,127,98],red:[182,83,76],slate:[111,127,143],mist:[242,246,245],line:[218,229,227],ink:[24,48,57],muted:[101,119,126],white:[255,255,255]};
 let y=20,pageScope='',pageMode='';
 const fmt=v=>typeof v==='number'&&Number.isFinite(v)?v.toLocaleString('en-IN',{minimumFractionDigits:0,maximumFractionDigits:2}):'—';
 const clean=v=>String(v??'—');
 const set=(name,bold=false,size=9)=>{doc.setFont('WPC',bold?'bold':'normal');doc.setFontSize(size);doc.setTextColor(...(C[name]||C.ink));};
 const room=h=>{if(y+h>270){doc.addPage();y=22;drawHeader();}};
 const text=(value,size=9,bold=false,color='ink',width=174)=>{set(color,bold,size);const lines=doc.splitTextToSize(clean(value),width);for(const line of lines){room(size*.43+2);doc.text(line,18,y);y+=size*.43+1.7;}y+=1.5;};
 const heading=(value,kicker='')=>{room(16);if(kicker)text(kicker.toUpperCase(),7.5,true,'teal');text(value,13,true,'navy');};
 const drawHeader=()=>{set('muted',false,7);doc.setDrawColor(...C.line);doc.line(18,13,192,13);doc.text('Water Potential Calculator',18,9);doc.text(`${pageMode} · ${pageScope}`.slice(0,75),192,9,{align:'right'});};
 const drawFooter=()=>{};
 const table=(columns,data,widths)=>{const drawRow=(cells,header=false)=>{doc.setFont('WPC',header?'bold':'normal');doc.setFontSize(7.7);const layouts=cells.map((cell,i)=>doc.splitTextToSize(clean(cell),widths[i]-4)),h=Math.max(1,...layouts.map(a=>a.length))*3.6+4;room(h);if(header){doc.setFillColor(...C.mist);doc.rect(18,y-3,174,h,'F');doc.setTextColor(...C.navy);}else doc.setTextColor(...C.ink);let x=18;layouts.forEach((lines,i)=>{doc.text(lines,x+2,y+1);x+=widths[i];});doc.setDrawColor(...C.line);doc.line(18,y+h-3,192,y+h-3);y+=h;};drawRow(columns,true);for(const r of data)drawRow(r);y+=5;};
 const kpi=(x,yy,w,label,value,sub,color='teal')=>{doc.setFillColor(...C[color]);doc.roundedRect(x,yy,w,27,2.5,2.5,'F');set('white',false,7.2);doc.text(label.toUpperCase(),x+4,yy+6);set('white',true,14);doc.text(value,x+4,yy+16);set('white',false,6.8);doc.text(sub,x+4,yy+23);};
 const barChart=(items,labelKey,valueKey,unit)=>{if(!items.length){text('No matching geography results.',9,false,'muted');return;}const max=Math.max(1,...items.map(d=>d[valueKey]||0));for(const d of items.slice(0,10)){room(8);set('ink',false,7.5);doc.text(clean(d[labelKey]).slice(0,32),18,y+2);doc.setFillColor(235,241,241);doc.rect(70,y-1,77,4,'F');doc.setFillColor(...C.teal);doc.rect(70,y-1,77*(d[valueKey]||0)/max,4,'F');set('navy',true,7.5);doc.text(`${fmt(d[valueKey])} ${unit}`,190,y+2,{align:'right'});y+=7;}y+=3;};
 const statusColor=s=>s==='Accepted'?'green':s==='Evidence pending'?'gold':s==='Calculated with warning'?'gold':s==='Excluded'?'slate':'slate';
 const dailyChart=trace=>{if(!trace?.length)return;text('Daily water-balance trace',10,true,'navy');text('Rainfall bars with closing storage line. Exact daily values remain available in the trace export.',7.5,false,'muted');room(52);const top=y,maxRain=Math.max(1,...trace.map(d=>d.rainfallMm||0)),maxStorage=Math.max(1,...trace.map(d=>d.closingStorageM3||0));doc.setDrawColor(...C.line);doc.line(18,top+38,192,top+38);doc.setFillColor(...C.cyan);const step=174/trace.length;for(let i=0;i<trace.length;i++){const h=(trace[i].rainfallMm||0)/maxRain*28;doc.rect(18+i*step,top+38-h,Math.max(.18,step*.75),h,'F');}doc.setDrawColor(...C.teal);doc.setLineWidth(.6);let px=18,py=top+38-(trace[0].closingStorageM3||0)/maxStorage*32;for(let i=1;i<trace.length;i++){const x=18+i/(trace.length-1)*174,v=top+38-(trace[i].closingStorageM3||0)/maxStorage*32;doc.line(px,py,x,v);px=x;py=v;}set('muted',false,6.5);doc.text(trace[0].date,18,top+44);doc.text(trace.at(-1).date,192,top+44,{align:'right'});y+=50;};

 for(const [ri,data] of reports.entries()){
  if(ri){doc.addPage();y=20;}pageScope=data.metadata.scope?.label||'Selected scope';pageMode=data.mode==='technical'?'Technical / M&E report':'Management report';
  // Cover page
  doc.setFillColor(...C.navy);doc.rect(0,0,210,70,'F');doc.setFillColor(...C.teal);doc.rect(0,70,210,8,'F');set('white',true,24);doc.text('Water Potential Calculator',18,31);set('white',false,10);doc.text('Water Potential · Participation · Reporting',18,42);set('navy',true,22);doc.text(data.mode==='technical'?'Technical / M&E Report':'Management Report',18,105);set('teal',true,14);doc.text(pageScope,18,118);set('ink',false,10);doc.text(`${data.metadata.reportingStartDate} to ${data.metadata.reportingEndDate}`,18,130);if(data.metadata.synthetic){doc.setFillColor(255,247,223);doc.roundedRect(18,143,174,15,2,2,'F');set('gold',true,8);doc.text('SAMPLE VALIDATION DATA · NOT FOR PROJECT REPORTING',23,152);}set('muted',false,8);doc.text('Generated '+new Date(data.generatedAt).toLocaleString('en-IN'),18,250);doc.setDrawColor(...C.line);doc.line(18,259,192,259);set('muted',false,7);doc.text('Decision-ready presentation of verified calculator results',18,266);
  // Summary page
  doc.addPage();y=24;drawHeader();heading('Executive summary','Results');text('Calculated values are presented for the selected scope. Missing, HOLD and excluded results are not treated as zero.',8.5,false,'muted');
  const visible=data.summary.filter(s=>!['WATER-EXCL','WATER-HOLD'].includes(s.component));let x=18,yy=y;for(const [i,s] of visible.slice(0,4).entries()){const w=41.2;kpi(x,yy,w,s.component,fmt(s.calculatedTotal),s.unit==='m3'?'m³ calculated':'person-days','teal');x+=44.2;if((i+1)%4===0){y=yy+32;x=18;yy=y;}}if(visible.length<4)y=yy+32;
  heading('Coverage and result status','Coverage');table(['Result','Records','Calculated','Not calculated / HOLD','Excluded'],data.summary.map(s=>[s.component,s.records,s.calculated,s.notCalculated,s.excluded]),[43,28,32,44,27]);
  const statusCounts={};for(const r of data.records)statusCounts[r.status]=(statusCounts[r.status]||0)+1;heading('Result status at a glance','Review');let sx=18;for(const [status,count] of Object.entries(statusCounts)){const color=statusColor(status);doc.setFillColor(...C[color]);doc.roundedRect(sx,y,40,16,2,2,'F');set('white',true,9);doc.text(String(count),sx+4,y+7);set('white',false,6.3);doc.text(status.slice(0,24),sx+4,y+13);sx+=43;if(sx>165){sx=18;y+=19;}}y+=22;
  if(data.geography.length){heading('Where the contribution comes from','Geography');const geo=data.geography.map(g=>({label:g.scope.label,value:g.summary.filter(s=>s.unit==='m3').reduce((a,s)=>a+(s.calculatedTotal||0),0)})).sort((a,b)=>b.value-a.value);barChart(geo,'label','value','m³');}
  heading('Included results','Results');table(['Structure / record','Result','Value','Status'],data.records.slice(0,data.mode==='management'?30:60).map(r=>[r.name||r.id,r.component,r.value==null?'—':`${fmt(r.value)} ${r.unit==='m3'?'m³':r.unit}`,r.status]),[66,31,36,41]);if(data.records.length>(data.mode==='management'?30:60))text(`${data.records.length-(data.mode==='management'?30:60)} additional records are available in the XLSX/CSV export.`,7.5,false,'muted');
  if(data.issues.length){heading('Items needing attention','Data review');text(`${data.issues.length} data-quality finding${data.issues.length===1?'':'s'} remain visible for this scope.`,8.5,false,'muted');table(['Finding','Level','Record'],data.issues.slice(0,20).map(i=>[i.message,i.severity,i.entityId||'Workbook']),[100,31,43]);}
  if(data.mode==='technical'){
   for(const r of data.records.filter(r=>r.unit==='m3').slice(0,20)){doc.addPage();y=24;drawHeader();heading(r.name||r.id,'Structure detail');text(`${r.structureType||'Structure'} · ${r.status}`,8.5,false,'muted');kpi(18,y,55,'Water potential',fmt(r.value),'m³','teal');kpi(77,y,55,'Calculation days',fmt(r.calculation.calculationDays),'days','navy');kpi(136,y,56,'Method',r.method.slice(0,18),'applied','green');y+=34;text(r.reason||'Calculation completed using the applicable method.',8.5,false,'ink');heading('Calculation basis','Technical');const c=r.calculation;table(['Basis','Value'],[['Calculation period',`${c.calculationStartDate||'—'} to ${c.calculationEndDate||'—'}`],['Eligible capacity',c.capacity?.eligibleCapacityM3==null?'—':fmt(c.capacity.eligibleCapacityM3)+' m³'],['Effective catchment',c.catchment?.effectiveHa==null?'—':fmt(c.catchment.effectiveHa)+' ha'],['Generated runoff',c.generatedRunoffM3==null?'—':fmt(c.generatedRunoffM3)+' m³'],['Captured runoff',c.capturedRunoffM3==null?'—':fmt(c.capturedRunoffM3)+' m³'],['Infiltration',c.cumulativeInfiltrationM3==null?'—':fmt(c.cumulativeInfiltrationM3)+' m³'],['Evaporation',c.cumulativeEvaporationM3==null?'—':fmt(c.cumulativeEvaporationM3)+' m³'],['Overflow',c.overflowM3==null?'—':fmt(c.overflowM3)+' m³'],['Final storage',c.finalClosingStorageM3==null?'—':fmt(c.finalClosingStorageM3)+' m³']],[74,100]);dailyChart(c.dailyTrace);text('Internal route, formula, hash and run identifiers are intentionally kept in the separate audit export rather than this practitioner report.',7.3,false,'muted');}
  }
 }
 const n=doc.getNumberOfPages();for(let i=1;i<=n;i++){doc.setPage(i);doc.setDrawColor(...C.line);doc.line(18,280,192,280);set('muted',false,7);doc.text('Water Potential Calculator',18,286);doc.text(`${i} / ${n}`,192,286,{align:'right'});}
 doc.setProperties({title:'Water Potential Calculator Report',subject:'Water potential and participation results',creator:'Water Potential Calculator'});return doc;
}
