export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const label=v=>String(v??'').replace(/_/g,' ');
export const number=v=>typeof v==='number'&&Number.isFinite(v)?v.toLocaleString(undefined,{minimumFractionDigits:0,maximumFractionDigits:2}):'—';
export const json=v=>`<pre class="technical-json">${esc(JSON.stringify(v,null,2))}</pre>`;
export const cards=rows=>`<section class="summary-card-grid">${rows.map(([l,v])=>`<article class="summary-card"><span>${esc(l)}</span><strong>${esc(typeof v==='number'?number(v):v??'—')}</strong></article>`).join('')}</section>`;
const tableModels=new Map();let tableId=0;
const tablePage=(rows,columns,page)=>{const size=50,slice=rows.slice(page*size,(page+1)*size);return `<div class="table-scroll" tabindex="0"><table style="min-width:${columns.length*112}px"><thead><tr>${columns.map(c=>`<th scope="col">${esc(c.label||c.key)}</th>`).join('')}</tr></thead><tbody>${slice.map(r=>`<tr>${columns.map(c=>`<td data-numeric="${typeof r[c.key]==='number'}" ${c.heat&&typeof r[c.key]==='number'?`style="background:rgba(39,128,113,${.08+.3*r[c.key]/Math.max(1,...rows.map(row=>typeof row[c.key]==='number'?row[c.key]:0))})"`:""}>${esc(c.format?c.format(r[c.key],r):r[c.key]===null||r[c.key]===undefined?'—':typeof r[c.key]==='object'?JSON.stringify(r[c.key]):r[c.key])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${!rows.length?'<p class="muted">No records in this selection.</p>':`<p class="table-pagination">${page*size+1}–${Math.min(rows.length,(page+1)*size)} of ${rows.length} records ${rows.length>size?`<button class="text-button" data-page-step="-1" ${page===0?'disabled':''}>Previous page</button><button class="text-button" data-page-step="1" ${(page+1)*size>=rows.length?'disabled':''}>Next page</button>`:''}</p>`}`;};
export function table(rows,columns){const id=String(++tableId);tableModels.set(id,{rows,columns,page:0});if(tableModels.size>150)tableModels.delete(tableModels.keys().next().value);return `<div data-paged-table="${id}">${tablePage(rows,columns,0)}</div>`;}
if(typeof document!=='undefined')document.addEventListener('click',e=>{const button=e.target.closest('[data-page-step]');if(!button)return;const box=button.closest('[data-paged-table]'),model=tableModels.get(box.dataset.pagedTable);if(!model)return;model.page+=Number(button.dataset.pageStep);box.innerHTML=tablePage(model.rows,model.columns,model.page);box.querySelector('.table-scroll').focus();});
export function action(main,selector,fn){main.querySelector(selector)?.addEventListener('click',async event=>{const b=event.currentTarget;b.disabled=true;try{await fn();}catch(e){let box=main.querySelector('[data-action-error]');if(!box){box=document.createElement('p');box.dataset.actionError='';box.setAttribute('role','alert');box.className='error-text';main.prepend(box);}box.textContent=e.message;}finally{b.disabled=false;}});}
